[supervisord]
nodaemon=true
pidfile=/home/user/supervisord.pid
logfile=/home/user/supervisord.log

[program:vnc]
command=/opt/start_vnc
stdout_logfile=/home/user/vnc.log
redirect_stderr=true
user=user
priority=10
autorestart=true
startsecs=1
startretries=5

[program:websockify_vnc]
command=websockify --web /usr/share/novnc 8080 localhost:5900
stdout_logfile=/home/user/websockify-vnc.log
redirect_stderr=true
user=user
priority=20
autorestart=true
startsecs=1
startretries=5

[program:koreader]
command=/opt/start_koreader
stdout_logfile=/home/user/koreader.log
redirect_stderr=true
user=user
priority=30
autorestart=true
startsecs=1
startretries=10
