[supervisord]
nodaemon=true
pidfile=/home/user/supervisord.pid
logfile=/home/user/supervisord.log

[program:vnc]
command=/opt/start_vnc
stdout_logfile=/home/user/vnc.log
redirect_stderr=true
user=user
priority=10

[program:websockify_vnc]
command=websockify --web /usr/share/novnc 8080 localhost:5900
stdout_logfile=/home/user/websockify-vnc.log
redirect_stderr=true
user=user
priority=20

[program:koreader]
command=/bin/bash /opt/start_koreader
autorestart=true
stdout_logfile=/home/user/koreader.log
redirect_stderr=true
user=user
priority=30
